#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GENERATED_DIR="$REPO_ROOT/generated/kind"
EXTRA_MOUNTS_DIR="$SCRIPT_DIR/extra-mounts"

ACTION="${1:-}"
shift || true

# Source kind.env so this script also works when called directly (not via cluster.sh).
# overrides.env + common.env are already loaded when called via cluster.sh; sourcing
# kind.env here is safe because it only sets variables that are not already set.
# shellcheck source=kind.env
source "$SCRIPT_DIR/kind.env"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

check_deps() {
    local missing=()
    command -v kind    >/dev/null 2>&1 || missing+=("kind")
    command -v kubectl >/dev/null 2>&1 || missing+=("kubectl")
    if (( ${#missing[@]} )); then
        echo "Error: missing dependencies: ${missing[*]}" >&2
        exit 1
    fi
}

cluster_exists() {
    kind get clusters 2>/dev/null | grep -qx "$KIND_CLUSTER_NAME"
}

build_extra_mounts_yaml() {
    local yaml=""
    shopt -s nullglob
    local pem_files=("$EXTRA_MOUNTS_DIR"/*.pem)
    shopt -u nullglob
    if (( ${#pem_files[@]} )); then
        yaml=$'\n''  extraMounts:'
        for f in "${pem_files[@]}"; do
            local base
            base="$(basename "$f")"
            yaml+=$'\n'"  - hostPath: ${f}"
            yaml+=$'\n'"    containerPath: /etc/ssl/certs/${base}"
            yaml+=$'\n'"    readOnly: true"
        done
    fi
    printf '%s' "$yaml"
}

render_cluster_config() {
    local mounts_yaml
    mounts_yaml="$(build_extra_mounts_yaml)"

    # Control-plane node block
    local cp_node="- role: control-plane"
    [[ -n "${KIND_NODE_IMAGE:-}" ]] && cp_node+=$'\n'"  image: ${KIND_NODE_IMAGE}"
    if [[ -n "${KIND_OIDC_URL:-}" ]]; then
        cp_node+=$'\n'"  kubeadmConfigPatches:"
        cp_node+=$'\n'"  - |"
        cp_node+=$'\n'"    kind: ClusterConfiguration"
        cp_node+=$'\n'"    apiServer:"
        cp_node+=$'\n'"      extraArgs:"
        cp_node+=$'\n'"        service-account-issuer: ${KIND_OIDC_URL}"
        cp_node+=$'\n'"        service-account-jwks-uri: ${KIND_OIDC_URL}/openid/v1/jwks"
    fi
    cp_node+="${mounts_yaml}"

    # Worker node block
    local worker_node="- role: worker"
    [[ -n "${KIND_NODE_IMAGE:-}" ]] && worker_node+=$'\n'"  image: ${KIND_NODE_IMAGE}"
    worker_node+="${mounts_yaml}"

    cat <<EOF
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: ${KIND_CLUSTER_NAME}
nodes:
${cp_node}
${worker_node}
EOF
}

write_cluster_info() {
    mkdir -p "$GENERATED_DIR"
    local server
    server="$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' 2>/dev/null || echo "")"
    local oidc_issuer="${KIND_OIDC_URL:-https://kubernetes.default.svc}"

    cat > "$GENERATED_DIR/cluster-info.env" <<EOF
# Generated by kind.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ") — do not edit manually.
# Source this file to get cluster variables in your shell:
#   source generated/kind/cluster-info.env

export KIND_CLUSTER_NAME="${KIND_CLUSTER_NAME}"
export KIND_CONTROL_PLANE_NODE="${KIND_CONTROL_PLANE_NODE}"
export KIND_WORKER_NODE="${KIND_WORKER_NODE}"
export KIND_SERVER="${server}"
export KIND_OIDC_ISSUER="${oidc_issuer}"
EOF

    echo ""
    echo "Cluster info written to: $GENERATED_DIR/cluster-info.env"
}

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------

case "$ACTION" in

  create)
    check_deps
    if cluster_exists; then
        echo "Error: cluster '${KIND_CLUSTER_NAME}' already exists." >&2
        echo "Run: cluster.sh destroy kind — then retry." >&2
        exit 1
    fi

    echo "==> Creating kind cluster: ${KIND_CLUSTER_NAME}"
    echo "    Nodes : ${KIND_CONTROL_PLANE_NODE}, ${KIND_WORKER_NODE}"
    [[ -n "${KIND_OIDC_URL:-}" ]] && echo "    OIDC  : ${KIND_OIDC_URL}"
    echo ""

    render_cluster_config | kind create cluster --config=-

    write_cluster_info

    if [[ -n "${KIND_OIDC_URL:-}" ]]; then
        echo ""
        echo "==> Publishing OIDC documents to GitHub Pages"
        bash "$SCRIPT_DIR/oidc-publish.sh"
    fi
    ;;

  destroy)
    check_deps
    if ! cluster_exists; then
        echo "Error: cluster '${KIND_CLUSTER_NAME}' does not exist." >&2
        exit 1
    fi

    echo "==> Deleting kind cluster: ${KIND_CLUSTER_NAME}"
    kind delete cluster --name "$KIND_CLUSTER_NAME"

    rm -f "$GENERATED_DIR/cluster-info.env"
    echo "Cluster destroyed. Generated env file removed."
    ;;

  info)
    if [[ -f "$GENERATED_DIR/cluster-info.env" ]]; then
        echo "Cluster info (generated/kind/cluster-info.env):"
        echo ""
        cat "$GENERATED_DIR/cluster-info.env"
    else
        echo "No cluster info found at $GENERATED_DIR/cluster-info.env" >&2
        echo "Has the cluster been created? Run: cluster.sh create kind" >&2
        exit 1
    fi
    ;;

  plan)
    check_deps
    echo "Note: kind uses shell scripts, not Terraform — 'plan' shows the config that would be used."
    echo ""
    render_cluster_config
    ;;

  "")
    echo "Error: action required. Valid actions: create | destroy | info | plan" >&2
    exit 1 ;;

  *)
    echo "Error: unknown action '$ACTION'. Valid: create | destroy | info | plan" >&2
    exit 1 ;;

esac
