#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TF_DIR="$SCRIPT_DIR/terraform"
GENERATED_DIR="$REPO_ROOT/generated/aws"

ACTION="${1:-}"
shift || true
EXTRA_ARGS=("$@")

# Source aws.env so this script also works when called directly (not via cluster.sh).
# overrides.env + common.env are already loaded when called via cluster.sh; sourcing
# aws.env here is safe because it only sets variables that are not already set.
# shellcheck source=aws.env
source "$SCRIPT_DIR/aws.env"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

fetch_local_ip() {
    local ip
    ip=$(curl -sf --max-time 5 https://checkip.amazonaws.com 2>/dev/null) ||
    ip=$(curl -sf --max-time 5 https://api.ipify.org 2>/dev/null) ||
    ip=$(curl -sf --max-time 5 https://ifconfig.me 2>/dev/null) || {
        echo "Error: could not determine local public IP. Check your internet connection." >&2
        exit 1
    }
    echo "${ip//[$'\r\n']}"   # strip any trailing newline/CR
}

tf() {
    terraform -chdir="$TF_DIR" "$@"
}

tf_output() {
    tf output -raw "$1" 2>/dev/null || echo ""
}

write_cluster_info() {
    mkdir -p "$GENERATED_DIR"

    local cluster_name endpoint oidc_issuer region vpc_id node_role_arn oidc_provider_arn
    cluster_name=$(tf_output cluster_name)
    endpoint=$(tf_output cluster_endpoint)
    oidc_issuer=$(tf_output cluster_oidc_issuer_url)
    region=$(tf_output aws_region)
    vpc_id=$(tf_output vpc_id)
    node_role_arn=$(tf_output node_role_arn)
    oidc_provider_arn=$(tf_output oidc_provider_arn)

    cat > "$GENERATED_DIR/cluster-info.env" <<EOF
# Generated by eks.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ") — do not edit manually.
# Source this file to get cluster variables in your shell:
#   source generated/aws/cluster-info.env

export EKS_CLUSTER_NAME="${cluster_name}"
export EKS_CLUSTER_ENDPOINT="${endpoint}"
export EKS_OIDC_ISSUER_URL="${oidc_issuer}"
export EKS_AWS_REGION="${region}"
export EKS_VPC_ID="${vpc_id}"
export EKS_NODE_ROLE_ARN="${node_role_arn}"
export EKS_OIDC_PROVIDER_ARN="${oidc_provider_arn}"
EOF

    echo ""
    echo "Cluster info written to: $GENERATED_DIR/cluster-info.env"
}

update_kubeconfig() {
    local cluster_name region
    cluster_name=$(tf_output cluster_name)
    region=$(tf_output aws_region)

    echo ""
    echo "Updating kubeconfig for cluster: $cluster_name (region: $region)"
    aws eks update-kubeconfig \
        --name "$cluster_name" \
        --region "$region" \
        --profile "${TF_VAR_aws_profile:-default}"

    echo "Run 'kubectl get nodes' to verify cluster access."
}

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------

case "$ACTION" in

  create)
    export TF_VAR_local_public_ip="$(fetch_local_ip)/32"
    echo "Local public IP: $TF_VAR_local_public_ip"

    echo ""
    echo "==> terraform init"
    tf init

    echo ""
    echo "==> terraform plan"
    tf plan -out="$TF_DIR/tfplan"

    echo ""
    echo "==> terraform apply"
    tf apply "$TF_DIR/tfplan"

    write_cluster_info
    update_kubeconfig
    ;;

  plan)
    export TF_VAR_local_public_ip="$(fetch_local_ip)/32"
    echo "Local public IP: $TF_VAR_local_public_ip"

    echo ""
    echo "==> terraform init"
    tf init

    echo ""
    echo "==> terraform plan"
    tf plan
    ;;

  destroy)
    export TF_VAR_local_public_ip="$(fetch_local_ip)/32"

    echo ""
    echo "==> terraform init"
    tf init

    echo ""
    echo "==> terraform destroy"
    tf destroy -auto-approve

    rm -f "$GENERATED_DIR/cluster-info.env"
    rm -f "$TF_DIR/tfplan"
    echo ""
    echo "Cluster destroyed. Generated env file removed."
    ;;

  info)
    if [[ -f "$GENERATED_DIR/cluster-info.env" ]]; then
        echo "Cluster info (generated/aws/cluster-info.env):"
        echo ""
        cat "$GENERATED_DIR/cluster-info.env"
    else
        echo "No cluster info found at $GENERATED_DIR/cluster-info.env" >&2
        echo "Has the cluster been created? Run: cluster.sh create aws" >&2
        exit 1
    fi
    ;;

  allow-ip)
    if [[ ${#EXTRA_ARGS[@]} -eq 0 ]]; then
        echo "Usage: cluster.sh allow-ip aws <CIDR> [CIDR...]" >&2
        exit 1
    fi

    export TF_VAR_local_public_ip="$(fetch_local_ip)/32"

    # Merge existing additional CIDRs with new ones passed as arguments.
    # TF_VAR_allowed_additional_CIDR must be a JSON array, e.g. '["1.2.3.0/24"]'
    existing="${TF_VAR_allowed_additional_CIDR:-[]}"
    new_json=$(printf '%s\n' "${EXTRA_ARGS[@]}" | jq -Rsc 'split("\n") | map(select(length > 0))')
    merged=$(jq -n --argjson existing "$existing" --argjson new "$new_json" \
        '$existing + $new | unique')
    export TF_VAR_allowed_additional_CIDR="$merged"

    echo "Allowed CIDRs after merge: $TF_VAR_allowed_additional_CIDR"
    echo ""
    echo "Note: to persist these CIDRs across sessions, add them to overrides.env:"
    echo "  export TF_VAR_allowed_additional_CIDR='${merged}'"
    echo ""

    tf init -upgrade=false

    echo ""
    echo "==> terraform plan"
    tf plan -out="$TF_DIR/tfplan"

    echo ""
    echo "==> terraform apply"
    tf apply "$TF_DIR/tfplan"
    ;;

  "")
    echo "Error: action required. Valid actions: create | plan | destroy | info | allow-ip" >&2
    exit 1 ;;

  *)
    echo "Error: unknown action '$ACTION'. Valid: create | plan | destroy | info | allow-ip" >&2
    exit 1 ;;

esac
